"""The data the backend stores, as Pydantic models.

A ``Project`` holds its files (``SourceFile``) and the steps run on it
(``Run``). ``ProjectStore`` saves that as JSON; ``NeonProjectStore`` saves the
same fields in Postgres. The
converter's output for one program is a ``PythonDraft``; a convert run keeps
one ``ConvertedProjectFile`` per program.

IDs are short numbers as text: projects ``"1"``, ``"2"``, ... across the app
(handed out by ``ProjectStore.next_id``), files and runs ``"1"``, ``"2"``, ...
within their project (handed out by ``ProjectService``). Timestamps fill
themselves in. The enums are ``StrEnum``, so each value is also its text.

Example:
    >>> project = Project(id="1", name="Payroll")
    >>> project.files, project.runs, project.files_added
    ([], [], 0)
    >>> RunStatus.DRAFT == "draft"
    True
"""

from datetime import UTC, datetime
from enum import StrEnum

from pydantic import BaseModel, Field


def utc_now() -> datetime:
    """Return the current time in UTC, used for ``created_at``.

    Returns:
        A timezone-aware ``datetime``.
    """
    return datetime.now(UTC)


class FileKind(StrEnum):
    """What a project file is, decided by its extension."""

    PROGRAM = "program"  # .cbl or .cob
    COPYBOOK = "copybook"  # .cpy
    DATA = "data"  # .dat


class RunKind(StrEnum):
    """Which pipeline step a run recorded."""

    ANALYZE = "analyze"
    CONVERT = "convert"
    VERIFY = "verify"


class RunStatus(StrEnum):
    """The outcome of a run, or of one converted file."""

    INVENTORY_ONLY = "inventory_only"  # analyze counted files; no dependency analysis yet
    DRAFT = "draft"  # converted with no review notes, but still unverified
    REVIEW_REQUIRED = "review_required"  # converted with lines marked TODO
    NOT_VERIFIED = "not_verified"  # verify ran without comparing COBOL and Python


class SourceFile(BaseModel):
    """One file stored in a project.

    Attributes:
        id: Number within its project, such as ``"1"``. Never reused.
        name: File name, such as ``PAY.cbl``.
        kind: Program, copybook, or data.
        content: The file's text.
    """

    id: str
    name: str
    kind: FileKind
    content: str


class PythonDraft(BaseModel):
    """What the converter produces for one COBOL program.

    Attributes:
        program_name: The name after ``PROGRAM-ID``.
        python: The generated Python script.
        notes: ``"Line N: <code>"`` for each line that was not converted.
    """

    program_name: str
    python: str
    notes: list[str]


class ConvertedFile(PythonDraft):
    """A ``PythonDraft`` plus the names of the input and output files.

    Attributes:
        source_name: The COBOL file name, such as ``PAY.cbl``.
        python_name: The generated file name, such as ``PAY.py``.
    """

    source_name: str
    python_name: str


class ConvertedProjectFile(ConvertedFile):
    """A ``ConvertedFile`` from a project, as saved in its convert run.

    Attributes:
        source_file_id: ID of the COBOL file it came from.
        status: ``draft`` or ``review_required``; never verified here.
    """

    source_file_id: str
    status: RunStatus


class FileCounts(BaseModel):
    """How many files of each kind a project has.

    Attributes:
        program_count: Number of ``.cbl``/``.cob`` files.
        copybook_count: Number of ``.cpy`` files.
        data_file_count: Number of ``.dat`` files.
    """

    program_count: int
    copybook_count: int
    data_file_count: int


class RunSummary(BaseModel):
    """A record that one pipeline step ran on a project.

    Attributes:
        id: Number within its project, in run order: ``"1"``, ``"2"``, ...
        kind: Which step ran.
        status: Its outcome.
        created_at: When it ran (UTC).
    """

    id: str
    kind: RunKind
    status: RunStatus
    created_at: datetime = Field(default_factory=utc_now)


class Run(RunSummary):
    """A ``RunSummary`` plus what the step produced.

    Where a field is typed ``RunSummary``, Pydantic writes only the summary
    fields, so run lists stay small.

    Attributes:
        files: The Python generated by a convert run; empty for other runs.
    """

    files: list[ConvertedProjectFile] = []


class Project(BaseModel):
    """A set of COBOL files and the history of steps run on them.

    Attributes:
        id: Number across the app, such as ``"1"``.
        name: Name given by the user.
        created_at: When the project was created (UTC).
        files: Stored files, in upload order.
        runs: Steps run so far, oldest first.
        files_added: How many files were ever added, including deleted ones.
            The next file's ID is this plus one. Saved, but not sent to clients.
    """

    id: str
    name: str
    created_at: datetime = Field(default_factory=utc_now)
    files: list[SourceFile] = []
    runs: list[Run] = []
    files_added: int = 0
