"""
ML-augmented COBOL → Python OOP refactorer (notebook Cell 4 logic).

Pipeline:
  1. Parse COBOL structure
  2. Cluster procedural paragraphs (unsupervised TF-IDF / KMeans)
  3. Emit one Python method per COBOL paragraph with translated statements
  4. Wire a ``run()`` entry point from the main paragraph
"""

from __future__ import annotations

from collections import defaultdict
from typing import Dict, List, Optional, Tuple

from src.cobol_parser import parse_cobol, parse_cobol_source
from src.models import cluster_procedural_patterns
from src.translator import (
    CobolTranslator,
    clean_identifier,
    default_value_for_pic,
    map_pic_to_type,
)


class OOPRefactorer:
    """Generate functionally oriented Python OOP from a COBOL program."""

    def __init__(self, use_ml_clustering: bool = True):
        self.use_ml_clustering = use_ml_clustering
        self._embedder = None  # lazy; notebooks import CodeEmbedder separately

    @property
    def embedder(self):
        """Lazy CodeEmbedder for notebook / analysis parity (not required for convert)."""
        if self._embedder is None:
            from src.models import CodeEmbedder

            self._embedder = CodeEmbedder()
        return self._embedder

    def _class_name(self, program_name: str) -> str:
        return clean_identifier(program_name).title().replace("_", "") + "Class"

    def _cluster_paragraphs(
        self, paragraphs: List[Tuple[str, str]]
    ) -> Dict[int, List[Tuple[str, str]]]:
        names = [n for n, _ in paragraphs]
        texts = [b if b.strip() else n for n, b in paragraphs]
        if self.use_ml_clustering and len(texts) >= 2:
            labels = cluster_procedural_patterns(
                texts, n_clusters=min(4, len(texts))
            )
        else:
            labels = list(range(len(texts)))
        groups: Dict[int, List[Tuple[str, str]]] = defaultdict(list)
        for label, name, body in zip(labels, names, [b for _, b in paragraphs]):
            groups[int(label)].append((name, body))
        return groups

    def _find_main_paragraph(self, paragraphs: List[Tuple[str, str]]) -> Optional[str]:
        for name, _ in paragraphs:
            upper = name.upper()
            if upper.startswith("MAIN") or upper.endswith("-MAIN") or upper == "MAIN":
                return name
        return paragraphs[0][0] if paragraphs else None

    def refactor_parsed(self, parsed: dict) -> str:
        """Generate Python source from an already-parsed COBOL dict."""
        fields = parsed.get("potential_attributes") or []
        paragraphs = parsed.get("raw_paragraphs") or []
        program_name = parsed.get("program_name") or "UNKNOWN"
        class_name = self._class_name(program_name)

        field_names = [item["name"] for item in fields]
        translator = CobolTranslator(field_names)
        clusters = self._cluster_paragraphs(paragraphs) if paragraphs else {}

        # Attribute declarations
        attr_lines: List[str] = []
        init_assigns: List[str] = []
        for item in fields:
            py_name = clean_identifier(item["name"])
            py_type = map_pic_to_type(item.get("pic", ""))
            default = default_value_for_pic(item.get("pic", ""))
            attr_lines.append(
                f"        self.{py_name}: {py_type} = {default}  # from PIC {item.get('pic', 'Unknown')}"
            )

        # Cluster summary comment for ML notebook parity
        cluster_comment_lines = [
            "    # === Procedural patterns grouped via unsupervised clustering ===",
        ]
        for cluster_id, group in sorted(clusters.items()):
            members = ", ".join(n for n, _ in group)
            cluster_comment_lines.append(
                f"    # Cluster {cluster_id}: {members}"
            )
        cluster_comment_lines.append("")

        code_lines: List[str] = [
            "from decimal import Decimal",
            "from typing import Any",
            "",
            f"class {class_name}:",
            '    """',
            f"    Modern OOP version of COBOL program: {program_name}",
            "    Generated by ML-Driven Legacy Code Modernization framework",
            '    """',
            "",
            "    def __init__(self):",
            "        # Data Division -> Class Attributes",
        ]
        if attr_lines:
            code_lines.extend(attr_lines)
        else:
            code_lines.append("        pass")
        code_lines.append("")
        code_lines.extend(cluster_comment_lines)
        code_lines.append(
            "    # === Business Logic Methods (one per COBOL paragraph) ==="
        )
        code_lines.append("")

        method_names: List[str] = []
        for name, body in paragraphs:
            method = clean_identifier(name)
            method_names.append(method)
            code_lines.append(f"    def {method}(self):")
            code_lines.append(f'        """COBOL paragraph: {name}"""')
            code_lines.extend(translator.translate_paragraph(body))
            code_lines.append("")

        main_para = self._find_main_paragraph(paragraphs)
        main_method = clean_identifier(main_para) if main_para else None

        code_lines.extend(
            [
                "    def run(self):",
                '        """Entry point - mirrors COBOL PROCEDURE DIVISION main flow."""',
                "        print('=== Starting modernized COBOL program ===')",
                f"        print(f'Program: {program_name}')",
            ]
        )
        if main_method and main_method in method_names:
            code_lines.append(f"        self.{main_method}()")
        elif method_names:
            code_lines.append(f"        self.{method_names[0]}()")
        else:
            code_lines.append("        pass")
        code_lines.extend(
            [
                "        print('=== Program completed successfully ===')",
                "",
                "    # Business logic preserved and modernized from original COBOL",
            ]
        )
        return "\n".join(code_lines)

    def refactor(self, cobol_file: str) -> str:
        """Refactor a COBOL file path into Python OOP source (notebook API)."""
        parsed = parse_cobol(cobol_file)
        return self.refactor_parsed(parsed)

    def refactor_source(self, source: str) -> str:
        """Refactor COBOL source text into Python OOP source (web / API)."""
        parsed = parse_cobol_source(source)
        return self.refactor_parsed(parsed)
